
name: windows-build
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller pillow PyQt5-sip

      - name: Ensure version file exists (auto-generate if missing)
        shell: pwsh
        run: |
          if (!(Test-Path app\version_info.txt)) {
            New-Item -ItemType Directory -Force -Path app | Out-Null
            $content = @(
              'VSVersionInfo(',
              '  ffi=FixedFileInfo(',
              '    filevers=(1, 0, 0, 0),',
              '    prodvers=(1, 0, 0, 0),',
              '    mask=0x3f,',
              '    flags=0x0,',
              '    OS=0x4,',
              '    fileType=0x1,',
              '    subtype=0x0,',
              '    date=(0, 0)',
              '  ),',
              '  kids=[',
              '    StringFileInfo([',
              "      StringTable('040904B0', [",
              "        StringStruct('CompanyName', 'MaWang0216_Luenah'),",
              "        StringStruct('FileDescription', 'Yujeong Desktop Pet'),",
              "        StringStruct('FileVersion', '4.0.0.0'),",
              "        StringStruct('InternalName', 'YujeongPet'),",
              "        StringStruct('LegalCopyright', '© 2025 MaWang0216_Luenah'),",
              "        StringStruct('OriginalFilename', 'YujeongPet.exe'),",
              "        StringStruct('ProductName', 'Yujeong Desktop Pet'),",
              "        StringStruct('ProductVersion', '4.0.0.0')",
              '      ])',
              '    ]),',
              "    VarFileInfo([VarStruct('Translation', [1033, 1200])])",
              '  ]',
              ')'
            )
            $content | Set-Content -Encoding ascii app\version_info.txt
          }

      - name: Prepare icon (png -> ico if needed)
        shell: pwsh
        run: |
          if (!(Test-Path icons\icon.ico) -and (Test-Path icons\icon.png)) {
            python -c "from PIL import Image; im=Image.open('icons/icon.png').convert('RGBA'); im.save('icons/icon.ico', sizes=[(16,16),(32,32),(48,48),(256,256)])"
          }

      - name: Show tree for debugging
        shell: pwsh
        run: |
          Get-ChildItem -Recurse -Force | Select-Object FullName
          Write-Host '--- version_info.txt ---'
          Get-Content app\version_info.txt

      - name: Build (PyInstaller onefile)
        shell: pwsh
        run: |
          pyinstaller app/main.py `
            --name YujeongPet `
            --noconsole `
            --onefile `
            --icon icons\icon.ico `
            --version-file app\version_info.txt `
            --hidden-import sip `
            --collect-submodules PyQt5 `
            --add-data "assets;assets" `
            --add-data "icons;icons"

      # ✅ secrets를 if에서 직접 쓰지 않고, 먼저 체크해서 출력값으로 노출
      - name: Check signing secrets
        id: signing
        shell: bash
        run: |
          if [ -n "${{ secrets.WIN_CSC_PFX }}" ] && [ -n "${{ secrets.WIN_CSC_PFX_PASSWORD }}" ]; then
            echo "enabled=true" >> "$GITHUB_OUTPUT"
          else
            echo "enabled=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Code sign (signtool)
        if: steps.signing.outputs.enabled == 'true'
        shell: pwsh
        env:
          PFX_BASE64: ${{ secrets.WIN_CSC_PFX }}
          PFX_PASSWORD: ${{ secrets.WIN_CSC_PFX_PASSWORD }}
        run: |
          [IO.File]::WriteAllBytes("codesign.pfx",[Convert]::FromBase64String($env:PFX_BASE64))
          $signtool = (Get-ChildItem "C:\Program Files (x86)\Windows Kits\10\bin" -Recurse -Filter signtool.exe |
                       Sort-Object FullName -Descending | Select-Object -First 1).FullName
          if (-not $signtool) { throw "signtool.exe not found" }
          & $signtool sign /f codesign.pfx /p $env:PFX_PASSWORD /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 dist\YujeongPet.exe `
            || & $signtool sign /f codesign.pfx /p $env:PFX_PASSWORD /tr http://timestamp.sectigo.com /td SHA256 /fd SHA256 dist\YujeongPet.exe

      - name: Zip artifact
        shell: pwsh
        run: |
          Compress-Archive -Path dist\YujeongPet.exe -DestinationPath dist\YujeongPet.zip -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: YujeongPet-Windows
          path: dist/YujeongPet.zip
